import mongoose from "mongoose";
const { Schema, model } = mongoose;

const administratorSchema = new Schema({
  id: { type: String, required: true, unique: true },
  username: { type: String, required: true },
  name: { type: String, required: true },
  password: { type: String, required: true },
  image: { type: String, required: true },
  twitter: { type: String, required: true },
  facebook: { type: String, required: true },
  linkedin: { type: String, required: true },
  role: { type: String, required: true, enum: ["super", "normal"] },
  datecreated: { type: Date, required: true, default: new Date() },
});

const articleSchema = new Schema({
  id: { type: String, required: true, unique: true },
  image: { type: String, required: true },
  title: { type: String, required: true },
  author: { type: String, required: true },
  post: { type: String, required: true },
  featured: { type: String, required: true, enum: ["true", "false"] },
  mainfeatured: { type: String, required: true, enum: ["true", "false"] },
  category: { type: String, required: true, enum: ["Job", "Scholarship"] },
  datecreated: { type: Date, required: true, default: new Date() },
});

const categorySchema = new Schema({
  id: { type: String, required: true, unique: true },
  categoryname: String,
});

const jobsSchema = new Schema({
  id: { type: String, required: true, unique: true },
  overview: { type: String, required: true },
  position: { type: String, required: true },
  image: { type: String, required: true },
  salary: { type: String, required: true },
  featured: { type: String, enum: ["true", "false"] },
  company: { type: String, required: true },
  website: { type: String, required: true },
  duration: { type: String, enum: ["Full Time", "Part Time"] },
  location: { type: String, required: true },
  responsibility: { type: String, required: true },
  requirements: { type: String, required: true },
  author: { type: String, required: true },
  jobcategory: { type: String, required: true },
  datecreated: { type: Date, default: new Date() },
});

const mailMessagesSchema = new Schema({
  id: { type: String, required: true, unique: true },
  receiver: { type: String, required: true },
  subject: { type: String, required: true },
  message: { type: String, required: true },
  datecreated: { type: Date, default: new Date() },
});

const scholarshipSchema = new Schema({
  id: { type: String, required: true, unique: true },
  image: { type: String, required: true },
  scholarshipname: { type: String, required: true },
  deadline: { type: Date, default: new Date() },
  description: { type: String, required: true },
  eligibility: { type: String, required: true },
  duration: { type: String, required: true },
  programsoffered: { type: String, required: true },
  benefits: { type: String, required: true },
  applicationinformation: { type: String, required: true },
  hostuniversity: { type: String, required: true },
  documentsrequired: { type: String, required: true },
  author: { type: String, required: true },
  datecreated: { type: Date, default: new Date() },
  agent: { type: String, required: true, enum: ["Agent", "No agent"] },
  featured: { type: String, required: true, enum: ["true", "false"] },
  scholarshiptype: {
    type: String,
    required: true,
    enum: ["Fully Funded", "Partially Funded"],
  },
  programs: {
    type: String,
    required: true,
    enum: [
      "All Levels",
      "Bachelors Degree",
      "Masters Degree",
      "Doctorate Degree",
      "Post Graduate Diploma",
    ],
  },
  scholarshipcategory: {
    type: String,
    required: true,
    enum: [
      "Government",
      "Private",
      "Organizational",
      "International",
      "Research",
    ],
  },
  country: {
    type: String,
    required: true,
    enum: [
      "Afghanistan",
      "Albania",
      "Algeria",
      "Andorra",
      "Angola",
      "Antigua & Deps",
      "Argentina",
      "Armenia",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bhutan",
      "Bolivia",
      "Bosnia Herzegovina",
      "Botswana",
      "Brazil",
      "Brunei",
      "Bulgaria",
      "Burkina",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Central African Rep",
      "Chad",
      "Chile",
      "China",
      "Colombia",
      "Comoros",
      "Congo",
      "Congo {Democratic Rep}",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "East Timor",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Fiji",
      "Finland",
      "France",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Honduras",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland {Republic}",
      "Israel",
      "Italy",
      "Ivory Coast",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea North",
      "Korea South",
      "Kosovo",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macedonia",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Mauritania",
      "Mauritius",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Morocco",
      "Mozambique",
      "Myanmar, {Burma}",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Poland",
      "Portugal",
      "Qatar",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "St Kitts & Nevis",
      "St Lucia",
      "Saint Vincent & the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome & Principe",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "Sudan",
      "Suriname",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Togo",
      "Tonga",
      "Trin_idad & Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Vatican City",
      "Venezuela",
      "Vietnam",
      "Yemen",
      "Zambia",
      "Zimbabwe",
    ],
  },
});

const subscribersSchema = new Schema({
  id: { type: String, required: true, unique: true },
  email: { type: String, required: true, lowercase: true },
});

const userLocationSchema = new Schema({
  id: { type: String, required: true, unique: true },
  ipAddress: { type: String, required: true },
  country: { type: String, required: true },
  city: { type: String, required: true },
  datecreated: { type: Date, default: new Date() },
});

const testimonialSchema = new Schema({
  id: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  image: { type: String, required: true },
  quote: { type: String, required: true },
  position: { type: String, required: true },
  author: { type: String, required: true },
  datecreated: { type: Date, default: new Date() },
});

const adminModel = model("Administrator", administratorSchema);
const articleModel = model("Article", articleSchema);
const categoryModel = model("Category", categorySchema);
const jobModel = model("Job", jobsSchema);
const mailMessagesModel = model("Mailmessages", mailMessagesSchema);
const scholarshipModel = model("Scholarship", scholarshipSchema);
const subscribersModel = model("Subscriber", subscribersSchema);
const userLocationModel = model("Userlocation", userLocationSchema);
const testimonialModel = model("Testimonial", testimonialSchema);

export {
  adminModel,
  articleModel,
  categoryModel,
  jobModel,
  mailMessagesModel,
  scholarshipModel,
  subscribersModel,
  userLocationModel,
  testimonialModel,
};
